CREATE TABLE information_item (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    information_type VARCHAR(32) NOT NULL,
    source VARCHAR(64) NOT NULL,
    source_item_id VARCHAR(255) NOT NULL,
    source_url VARCHAR(2048) NULL,
    title VARCHAR(1000) NOT NULL,
    content LONGTEXT NULL,
    publish_time DATETIME(3) NULL,
    collected_at DATETIME(3) NOT NULL,
    first_seen_time DATETIME(3) NOT NULL,
    last_seen_time DATETIME(3) NOT NULL,
    content_hash CHAR(64) NOT NULL,
    current_version_no INT UNSIGNED NOT NULL DEFAULT 1,
    raw_payload JSON NOT NULL,
    schema_version INT UNSIGNED NOT NULL,
    collector_id VARCHAR(128) NOT NULL,
    collector_version VARCHAR(64) NOT NULL,
    collection_context JSON NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_information_item_identity (source, information_type, source_item_id),
    KEY idx_information_item_type_last_seen (information_type, last_seen_time),
    KEY idx_information_item_source_last_seen (source, last_seen_time),
    KEY idx_information_item_status_last_seen (status, last_seen_time),
    KEY idx_information_item_publish_time (publish_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE job_information (
    information_id BIGINT UNSIGNED NOT NULL,
    source_company_id VARCHAR(255) NULL,
    source_recruiter_id VARCHAR(255) NULL,
    company_name VARCHAR(255) NULL,
    company_url VARCHAR(2048) NULL,
    company_scale_text VARCHAR(100) NULL,
    company_stage_text VARCHAR(100) NULL,
    company_industry_text VARCHAR(255) NULL,
    salary_text VARCHAR(100) NULL,
    salary_source VARCHAR(32) NULL,
    salary_min_monthly_yuan INT UNSIGNED NULL,
    salary_max_monthly_yuan INT UNSIGNED NULL,
    salary_months TINYINT UNSIGNED NULL,
    location_name VARCHAR(255) NULL,
    city_name VARCHAR(100) NULL,
    area_name VARCHAR(100) NULL,
    business_district_name VARCHAR(100) NULL,
    experience_text VARCHAR(100) NULL,
    education_text VARCHAR(100) NULL,
    recruiter_name VARCHAR(255) NULL,
    recruiter_title VARCHAR(255) NULL,
    recruiter_active_text VARCHAR(100) NULL,
    remote_type VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    job_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    detail_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    detail_collected_at DATETIME(3) NULL,
    source_tags JSON NULL,
    source_skill_tags JSON NULL,
    welfare JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (information_id),
    KEY idx_job_information_source_company_id (source_company_id),
    KEY idx_job_information_source_recruiter_id (source_recruiter_id),
    KEY idx_job_information_company_name (company_name),
    KEY idx_job_information_city_name (city_name),
    KEY idx_job_information_status_updated_at (job_status, updated_at),
    KEY idx_job_information_remote_updated_at (remote_type, updated_at),
    KEY idx_job_information_salary_range (salary_min_monthly_yuan, salary_max_monthly_yuan),
    KEY idx_job_information_detail_status (detail_status),
    CONSTRAINT fk_job_information_information_item
        FOREIGN KEY (information_id) REFERENCES information_item (id)
        ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE information_snapshot (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    information_id BIGINT UNSIGNED NOT NULL,
    version_no INT UNSIGNED NOT NULL,
    content_hash CHAR(64) NOT NULL,
    title VARCHAR(1000) NOT NULL,
    content LONGTEXT NULL,
    standardized_payload JSON NOT NULL,
    raw_payload JSON NOT NULL,
    collected_at DATETIME(3) NOT NULL,
    collector_id VARCHAR(128) NOT NULL,
    collector_version VARCHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_information_snapshot_version (information_id, version_no),
    KEY idx_information_snapshot_hash (information_id, content_hash),
    KEY idx_information_snapshot_created_at (information_id, created_at),
    CONSTRAINT fk_information_snapshot_information_item
        FOREIGN KEY (information_id) REFERENCES information_item (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
